### ISSUE TITLE
一些问题咨询

### ISSUE THREAD

**Issue by zhangjiahui-199609** [domneedham/GameShop#1]
想问一下这个里面的fxml是什么意思啊，这个是什么类型的项目呢？

**Comment by domneedham** [comment]
> 想问一下这个里面的fxml是什么意思啊，这个是什么类型的项目呢？

It is a JavaFX project and the FXML is the markup style used to generate the screens. Similar layout style to HTML, except this is for the JavaFX library.

**Comment by zhangjiahui-199609** [comment]
wow,这是我第一次看到这个开发工具，👍👍👍发自我的Huawei手机-------- 原始邮件 --------主题：Re: [domneedham/GameShop] 一些问题咨询 (#1)发件人：Dom Needham 收件人：domneedham/GameShop 抄送：zhangjiahui-199609 <627837879@qq.com>,Author 



想问一下这个里面的fxml是什么意思啊，这个是什么类型的项目呢？



It is a JavaFX project and the FXML is the markup style used to generate the screens. Similar layout style to HTML, except this is for the JavaFX library.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/domneedham/GameShop/issues/1#issuecomment-611533867",

"url": "https://github.com/domneedham/GameShop/issues/1#issuecomment-611533867",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
